clusterName: example
clusterDomain: example.com
email: jondoe@example.com

certManager:
  enabled: false
  ingressCertificate:
    enabled: false
    secretName: ''

vaultSecrets:
  enabled: false
  organizationID: ''
  projectID: ''
  servicePrincipal:
    clientID: ''
    clientSecret: ''
    name: ''
  app:
    refreshAfter: ''
    name: ''
    key: ''

lvmstorage:
  enabled: false

aap:
  enabled: false

ocpVirtualization:
  enabled: false

nfs:
  enabled: false

  namespace: '' #nfs
  server: '' #pve2.batchelor.live
  path: '' #/nfs/storage-class

  provisioner:
    name: '' #nfs-storage
    service_account: '' #nfs-client-provisioner