{{- if .Values.nfs.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-scc-hostmount-anyuid
  namespace: {{ .Values.nfs.namespace | default "nfs" }}
rules:
  - apiGroups: 
    - "security.openshift.io"
    resources: 
    - "securitycontextconstraints"
    resourceNames: 
    - "hostmount-anyuid"
    verbs: 
    - "use"
---
{{- end -}}