{{- if .Values.nfs.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nfs-scc-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-scc-hostmount-anyuid
subjects:
  - kind: ServiceAccount
    name: {{ .Values.provisioner.service_account }}
    namespace: {{ .Values.nfs.namespace }}
{{- end -}}