{{- if .Values.vaultSecrets.enabled -}}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: vault-secrets-operator-group
  namespace: openshift-operators
spec:
  targetNamespaces:
    - openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-secrets-operator
  namespace: openshift-operators
spec:
  channel: {{ index .Values.vaultSecrets.subscription.channel 0 | default "stable" }}
  installPlanApproval: {{ .Values.vaultSecrets.subscription.installPlanApproval | default "Automatic" }}
  name: vault-secrets-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ index .Values.vaultSecrets.subscription.startingCSV 0 | default "vault-secrets-operator.v0.5.2" }}
---
kind: Secret
apiVersion: v1
metadata:
  name: hashicorp-service-principal
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  clientID: {{ .Values.vaultSecrets.clientID | default "" }}
  clientSecret: {{ .Values.vaultSecrets.clientSecret | default "" }}
---
{{- end -}}