{{- if .Values.vaultSecrets.enabled -}}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-secrets-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/vault-secrets-operator.openshift-operators: ''
spec:
  channel: {{ index .Values.vaultSecrets.subscription.channel 0 | default "stable" }}
  installPlanApproval: {{ .Values.vaultSecrets.subscription.installPlanApproval | default "Automatic" }}
  name: vault-secrets-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ index .Values.vaultSecrets.subscription.startingCSV 0 | default "vault-secrets-operator.v0.7.1" }}
---
kind: Secret
apiVersion: v1
metadata:
  name: hashicorp-service-principal
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  clientID: {{ .Values.vaultSecrets.clientID | default "" }}
  clientSecret: {{ .Values.vaultSecrets.clientSecret | default "" }}
---
kind: Secret
apiVersion: v1
metadata:
  name: hashicorp-service-principal
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  clientID: {{ .Values.vaultSecrets.clientID | default "" }}
  clientSecret: {{ .Values.vaultSecrets.clientSecret | default "" }}
---
{{- end -}}