{{- if .Values.cert_manager.enabled -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cert-manager-operator
  namespace: cert-manager-operator
spec:
  targetNamespaces:
  - cert-manager-operator
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cert-manager
  namespace: openshift-operators
spec:
  channel: {{ .Values.cert_manager.subscription.channel | default "stable" }}
  installPlanApproval: {{ .Values.cert_manager.subscription.installPlanApproval | default "Automatic" }}
  name: cert-manager
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.cert_manager.subscription.starting_csv | default "cert-manager.v1.14.2" }}
---
{{- end -}}