{{- if .Values.certManager.enabled -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: openshift-operators
spec:
  channel: {{ index .Values.certManager.subscription.channel 0 | default "stable" }}
  installPlanApproval: {{ .Values.certManager.subscription.installPlanApproval | default "Automatic" }}
  name: cert-manager
  source: community-operators
  sourceNamespace: openshift-marketplace
---
{{- end -}}