{{- if .Values.certManager.ingressCertificate.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - '*.apps.{{ .Values.clusterName | default "ocp" }}.{{ .Values.clusterDomain | default "example.com" }}'
  secretName: ingress-certificate-secret
---
{{- end -}}