{{- if .Values.certManager.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  acme:
    email: {{ .Values.email | default "jondoe@example.com" }}
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: {{ .Values.vaultSecrets.app.key | default "example-api-key" }}
              name: hcp-{{ .Values.vaultSecrets.app.name | default "homelab" }}-secrets
        selector: 
          dnsZones:
            - {{ .Values.clusterDomain | default "example.com" }}
---
{{- end -}}