{{- if .Values.aap.enabled -}}
---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  admin_password_secret: hcp-aap-secrets
  route_tls_termination_mechanism: Edge
  no_log: true
  redis_mode: standalone
  api:
    log_level: INFO
    replicas: 1
  database:
    postgres_data_volume_init: false
  
---
{{- end -}}