{{- if .Values.aap.enabled -}}
---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: ansible-automation-platform
spec:
  route_tls_termination_mechanism: Edge
  no_log: true
  redis_mode: standalone
  api:
    log_level: INFO
    replicas: 1
  database:
    postgres_data_volume_init: false
  hostname: aap.apps.sno.batchelor.live
  # hub:
  #   disabled: false
  #   ## Modify to contain your RWM storage class name
  #   storage_type: file
  #   file_storage_storage_class: lvms-vg1
  #   file_storage_size: 10Gi
---
{{- end -}}