{{- if .Values.lvmstorage.enabled -}}
---
apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
  annotations:
    storageclass.kubernetes.io/is-default-class": "true"
spec:
  storage:
    deviceClasses:
      - default: true
        fstype: xfs
        thinPoolConfig:
          sizePercent: 90
          name: thin-pool-1
          overprovisionRatio: 10
        name: vg1
---
{{- end -}}