apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-root-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/JustinBatchelor/openshift-operators
    targetRevision: HEAD
    path: ./
    helm:
      parameters:
        - name: clusterName
          value: "dev"
        - name: clusterDomain
          value: "batchelor.live"
        - name: email
          value: "justinrossbatchelor@gmail.com"
        - name: certManager.enabled
          value: "true"
        - name: certManager.ingressCertificate.enabled
          value: "false"
        - name: vaultSecrets.enabled
          value: "true"
        - name: vaultSecrets.organizationID
          value: "xxxx"
        - name: vaultSecrets.projectID
          value: "xxx"
        - name: vaultSecrets.servicePrincipal.clientID
          value: "xxx"
        - name: vaultSecrets.servicePrincipal.clientSecret
          value: "xxx"
        - name: vaultSecrets.servicePrincipal.name
          value: "hcp-service-principal"
        - name: vaultsecrets.app.name
          value: "homelab"
        - name: vaultsecrets.app.key
          value: "cloudflare_api_token"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
