apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-root-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/JustinBatchelor/openshift-operators
    targetRevision: HEAD
    path: ./
    helm:
      parameters:
        - name: clusterName
          value: "dev"
        - name: clusterDomain
          value: "batchelor.live"
        - name: email
          value: "justinrossbatchelor@gmail.com"
        - name: certManager.enabled
          value: "true"
        - name: certManager.ingressCertificate
          value: "false"        
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true