apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-root-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/JustinBatchelor/openshift-operators
    targetRevision: certmanager
    path: ./
    helm:
      parameters:
        - name: cert_manager.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true