{{- if .Values.ocpVirtualization.enabled -}}
---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  annotations:
    deployOVS: 'false'
    argocd.argoproj.io/sync-wave: "10"
  namespace: openshift-cnv
spec:
  uninstallStrategy: RemoveWorkloads
---
{{- end -}}