apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-role
rules:
- apiGroups: 
  - "cert-manager.io"
  - "project.openshift.io"
  - "secrets.hashicorp.com"
  - "lvm.topolvm.io"
  - "automationcontroller.ansible.com"
  - "hco.kubevirt.io"
  - ""
  resources:
  - "clusterissuers"
  - "certificates"
  - "projects"
  - "hcpauths"
  - "hcpvaultsecretsapps"
  - "secrets"
  - "lvmclusters"
  - "automationcontrollers"
  - "hyperconvergeds"
  - "deployments"
  - "statefulsets"
  verbs: 
  - "get" 
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"