apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-rolebinding
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: cert-manager
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-storage
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: nfs
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: sso
roleRef:
  kind: ClusterRole
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
