apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-role
rules:
- apiGroups: 
{{- if .Values.certManager.enabled }}
  - "cert-manager.io"
{{- end }}
  resources:
{{- if .Values.certManager.enabled }}
  - "clusterissuers"
{{- end }}
{{- if .Values.certManager.ingressCertificate }}
  - "certificates"
{{- end }}
  verbs: 
  - "get" 
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"