{{- if .Values.sso.enabled -}}
---
kind: Keycloak
apiVersion: keycloak.org/v1alpha1
metadata:
  name: keycloak
  labels:
    app: sso
  namespace: sso
spec:
  instances: 1
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: SSO_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: ADMIN_USERNAME
              name: sso-admin-credential
        - name: SSO_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ADMIN_PASSWORD
              name: sso-admin-credential
---
{{- end -}}