{{- if .Values.sso.enabled -}}
---
kind: Keycloak
apiVersion: keycloak.org/v1alpha1
metadata:
  name: keycloak
  labels:
    app: sso
  namespace: sso
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  instances: 1
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: SSO_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: admin_username
              name: sso-admin-credential
        - name: SSO_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin_password
              name: sso-admin-credential
---
{{- end -}}